# backend/app/schemas/submission.py

from pydantic import BaseModel, HttpUrl

# --- Schemas for OCR Processing ---

class OCRRequest(BaseModel):
    """
    Schema for the request body of the OCR endpoint.
    It expects a valid GCS URL for the image.
    """
    image_gcs_url: str

    model_config = {
        "json_schema_extra": {
            "examples": [
                {
                    "image_gcs_url": "gs://your-bucket-name/path/to/image.jpg"
                }
            ]
        }
    }


class OCRResponse(BaseModel):
    """
    Schema for the response body of the OCR endpoint.
    It returns the extracted text.
    """
    ocr_text: str

# --- Schemas for AI Feedback Generation ---

class AIFeedbackRequest(BaseModel):
    """
    Schema for the request body of the AI feedback generation endpoint.
    It expects the OCR'd text from the user's submission.
    """
    ocr_text: str
    # In the future, we might add problem_id here to fetch the canonical solution
    # problem_id: str

class AIFeedbackResponse(BaseModel):
    """
    Schema for the response body of the AI feedback generation endpoint.
    It returns the feedback generated by the AI.
    """
    ai_feedback: str